### ISSUE TITLE
lib.wlk - Bad description for method addVisualIn() in object game

### ISSUE THREAD

**Issue by LeaTex** [uqbar-project/wollok-site#14]
Method `addVisualIn()` has incorrct description because it refers to `addVisual()`

Must fix line 168 in lib.html
https://github.com/uqbar-project/wollok-site/blob/master/documentacion/wollokdoc/lib.html#L168

![imagen](https://user-images.githubusercontent.com/6115573/56710310-dea9b880-66fb-11e9-8b5c-351534af4a97.png)

**Comment by fdodino** [comment]
Solved in Wollok 1.8.2 deploy
