### ISSUE TITLE
la seccion de errores comunes de instalacion anda mal

### ISSUE THREAD

**Issue by lspigariol** [uqbar-project/wollok-site#15]
desde
https://www.wollok.org/instalacion/

el link de "guia de solucion... " no lo muestra desplegado

y luego, no se puede acceder a
https://www.wollok.org/instalacion/#apuntando-la-jdk-correcta-en-ini-de-wollok

**Comment by fdodino** [comment]
La solución rápida es agrandar todas las secciones. Eso es lo que voy a hacer, porque más laburo requeriría agregar javascript, cosa que prefiero por el momento no hacer para mantener simple las páginas
