### ISSUE TITLE
link de atajos en apuntes manda a otro link

### ISSUE THREAD

**Issue by pablommendez** [uqbar-project/wollok-site#17]
el link de atajos de wollok en la sección de documentación redirecciona a la guía de git.

**Comment by faloi** [comment]
@fdodino @npasserini @lspigariol yo enconré este: https://docs.google.com/document/d/1A6JB4EretksCyMDvOj4NzfiEzX8yfboDTZnER7x_xJI/edit

¿Es el correcto? Si es así ya lo cambio.

**Comment by fdodino** [comment]
sí!!! Gracias Fede!

**Comment by faloi** [comment]
Gracias a @pablommendez (estudiante de UNaHur) que vio el bug y se animó a reportarlo.

PD: ya que ahora en general conocen Git y GitHub, podríamos agregar un botoncito por algún lado que aliente a crear una issue. Creo otra issue para eso.
