### ISSUE TITLE
Agregar un botón o sección para reportar errores del sitio

### ISSUE THREAD

**Issue by faloi** [uqbar-project/wollok-site#18]
Ya que una gran mayoría de lxs estudiantes que usan Wollok también conocen Git y GitHub, me parece piola agregar por algún lado un botoncito "¿Encontraste un error?" que directamente lleve a https://github.com/uqbar-project/wollok-site/issues/new.

Ver, por ejemplo, #17, que fue creada por un estudiante (que justo estaba en clase conmigo y me dijo... porque si no lo hubiésemos perdido). 

¿Qué les parece?

**Comment by PalumboN** [comment]
Hay un link a los issues de Wollok (no del site, pero para mi está mejor para centralizar) al final de https://www.wollok.org/instalacion/ 

Tal vez estaría bueno mover eso al inicio o a la tab de Comunidad. Qué les parece?

**Comment by npasserini** [comment]
Todo sí. Me da lo mismo si los centralizamos o no, pero está bueno que
tengamos un botón.

**Comment by fdodino** [comment]
lo voy a poner en la página principal, pero para mí es como dice Fede, apuntando a wollok-site y haciendo hincapié en que lo que falta es documentación o bien hay errores en la página. De última si vemos que muchos empiezan a cargar issues que deberían ser de wollok cambiamos el link...

En instalación dejo el otro link.
