### ISSUE TITLE
Update of the JDK to 1.8 in Windows, avoid openning wollok properly

### ISSUE THREAD

**Issue by vpennella** [uqbar-project/wollok-site#2]
When you get the JDK 1.8 just using the java update, you can't open Wollok properly and will get an error exit code = 13. I have attached an screen shot of the error.

![error](https://cloud.githubusercontent.com/assets/10461931/18418632/502c38ac-7820-11e6-8d27-3b036ab8c25a.jpg)
One way to fix the issue is to download the JDK from the page and install it.

**Comment by fdodino** [comment]
Added to instalacion.md and download.md page
