### ISSUE TITLE
Renombrar 'variables de instancia' => 'atributos'

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok-site#23]
El término variable de instancia tiene dos problemas
1) Lo usamos antes de tener clases, donde la palabra instancia no tiene sentido y confunde.
2) Pueden ser constantes.

El término atributo además de evitar estos problemas me parece más prolijo para evitar confusiones y se usa en muchos lugares en la industria y en la academia. De yapa es más corto.

**Comment by lspigariol** [comment]
tal vez me adelanté o debería haberlo preguntado...
pero en el  PR que hice ayer ya está modificado!

**Comment by npasserini** [comment]
Genial!
