### ISSUE TITLE
Accesors property heredados - Chequeador de tipos

### ISSUE THREAD

**Issue by BrianDamianLuna** [uqbar-project/wollok-site#27]
Buenas!

Les reporto este pequeño bug del chequeador de tipos que encontré. Resulta que al heredar de una clase que tiene atributos definidos como property, el chequeador de tipos no detecta los accesors heredados en la subclase.

En tiempo de ejecución todo va bien, el problema es solo en el entorno.

Saludos!

**Comment by npasserini** [comment]
Muchas gracias Brian por el reporte!

**Comment by fdodino** [comment]
Gracias @BrianDamianLuna !! , cargamos este issue: https://github.com/uqbar-project/wollok/issues/1748, y está disponible para testear en la versión de Wollok 1.9.2 que fue liberada en diciembre 2019. Cierro el ticket.
