### ISSUE TITLE
Problema para descargar Wollok

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-site#37]
Estoy usando Chrome - Version 86.0.4240.111 (Official Build) (64-bit), y cuando intento descargar Wollok desde el sitio no pasa nada (nunca comienza la descarga).

Mirando la consola salta este error:
```
Mixed Content: The site at 'https://www.wollok.org/' was loaded over a secure connection, but the file at 'http://wollokdownload.s3-website-us-west-2.amazonaws.com/wollok/products/stable/wollok-linux.gtk.x86_64.zip' was redirected through an insecure connection. This file should be served over HTTPS. This download has been blocked. See https://blog.chromium.org/2020/02/protecting-users-from-insecure.html for more details.
```
- Al parecer el problema es que el sitio es https y el link de la descarga http.
- Si hago click en el link http que aparece en el error de la consola sí comienza a descargar (o sea, el link funciona).

**Comment by juanbono** [comment]
Probe cambiar en la página los links pero no funciona, porque luego los enlaces redirigen a una dirección con http :(

**Comment by fdodino** [comment]
uf @tesonep podemos generar links vía https?

**Comment by tesonep** [comment]
Efectivamente este es el problema. Le cambio el aceite al generador de excusas y me fijo.

**Comment by fdodino** [comment]
jajajajaj, sos un grande!

**Comment by tesonep** [comment]
Estoy teniendo algunos problemas para hacer el redirect, estoy viendo que es lo mejor. Se puede hacer una version medio rapida usando la maquina de wollok.game como proxy, pero estoy viendo si se puede evitar el doble request.

**Comment by PalumboN** [comment]
Avisá si necesitás una mano @tesonep.

Por ahora el _workaround_ que estoy sugiriendo a mis estudiantes (por si alguien llega al issue con el problema) es:
- Descarga con la opción de `click derecho > guardar como...`. Lo que fuerza la descarga.
![Selection_381](https://user-images.githubusercontent.com/4098184/113713339-98b64700-96bd-11eb-9724-0d72f33fd5ed.png)

- Decirle al navegador que estamos segurxs de descargar el archivo.
![Selection_383](https://user-images.githubusercontent.com/4098184/113713443-bbe0f680-96bd-11eb-8548-42444094b0bc.png)

**Comment by fdodino** [comment]
@PalumboN : ahí subí los `zip` a los releases del repositorio directamente en wollok y reapunté los links. Hay que reapuntarlos manualmente por ahora (a futuro podemos hacer un script que lo haga), pero ya funcionan. Los links de 32 bits no los corregí todavía, después los subo.
